# Generated by Django 6.0.6 on 2026-06-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='dokumanlar/'),
        ),
    ]
