# Generated by Django 6.0.6 on 2026-06-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_uploaded_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='Açıklama',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Fiyat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uploaded_file',
            new_name='Resim',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='İsim',
        ),
    ]
